create table if not exists schools (
  id int generated by default as identity primary key,
  name citext not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_schools_updated_at on schools;
create trigger trg_schools_updated_at
before update on schools for each row execute function update_updated_at_column();

create index if not exists schools_name_trgm on schools using gin (name gin_trgm_ops);
