create table if not exists fields_of_work (
  id int generated by default as identity primary key,
  name citext not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_fields_of_work_updated_at on fields_of_work;
create trigger trg_fields_of_work_updated_at
before update on fields_of_work for each row execute function update_updated_at_column();

create index if not exists fow_name_trgm on fields_of_work using gin (name gin_trgm_ops);
