create table if not exists companies (
  id int generated by default as identity primary key,
  name citext not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_companies_updated_at on companies;
create trigger trg_companies_updated_at
before update on companies for each row execute function update_updated_at_column();

create index if not exists companies_name_trgm on companies using gin (name gin_trgm_ops);
