create table if not exists majors (
  id int generated by default as identity primary key,
  name citext not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_majors_updated_at on majors;
create trigger trg_majors_updated_at
before update on majors for each row execute function update_updated_at_column();

create index if not exists majors_name_trgm on majors using gin (name gin_trgm_ops);

-- Wire to profiles (you already have major_id int)
do $$ begin
  alter table profiles
    add constraint fk_profiles_major
    foreign key (major_id) references majors(id) on delete set null;
exception when duplicate_object then null; end $$;

create index if not exists idx_profiles_major_id on profiles(major_id);
