create extension if not exists citext;
create extension if not exists pg_trgm;

create table if not exists programs (
  id int generated by default as identity primary key,
  name citext not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_programs_updated_at on programs;
create trigger trg_programs_updated_at
before update on programs for each row execute function update_updated_at_column();

create index if not exists programs_name_trgm on programs using gin (name gin_trgm_ops);

-- Wire to profiles (you already have program_id int)
do $$ begin
  alter table profiles
    add constraint fk_profiles_program
    foreign key (program_id) references programs(id) on delete set null;
exception when duplicate_object then null; end $$;

create index if not exists idx_profiles_program_id on profiles(program_id);
