create table if not exists skills (
  id int generated by default as identity primary key,
  name citext not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_skills_updated_at on skills;
create trigger trg_skills_updated_at
before update on skills for each row execute function update_updated_at_column();

create index if not exists skills_name_trgm on skills using gin (name gin_trgm_ops);

create table if not exists profile_skills (
  profile_id uuid not null references profiles(id) on delete cascade,
  skill_id   int  not null references skills(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, skill_id)
);
create index if not exists idx_profile_skills_skill on profile_skills(skill_id);
